
#include "M6502Asm.h"

namespace M6502 {
namespace Asm {

const struct metadata instructions[256] =
{
    {2, 7, IMP, "BRK", rflags: 0, wflags: 0},
    {2, 6, INX, "ORA", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 8, INX, "SLO", rflags: 0, wflags: 0, unofficial : 1},
    {2, 3, ZPG, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 3, ZPG, "ORA", rflags: 0, wflags: 0},
    {2, 5, ZPG, "ASL", rflags: 0, wflags: 0},
    {2, 5, ZPG, "SLO", rflags: 0, wflags: 0, unofficial : 1},
    {1, 3, IMP, "PHP", rflags: 0, wflags: 0},
    {2, 2, IMM, "ORA", rflags: 0, wflags: 0},
    {1, 2, ACC, "ASL", rflags: 0, wflags: 0},
    {2, 2, IMM, "AAC", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABS, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABS, "ORA", rflags: 0, wflags: 0},
    {3, 6, ABS, "ASL", rflags: 0, wflags: 0},
    {3, 6, ABS, "SLO", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, REL, "BPL", rflags: 0, wflags: 0},
    {2, 5, INY, "ORA", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 8, INY, "SLO", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "ORA", rflags: 0, wflags: 0},
    {2, 6, ZPX, "ASL", rflags: 0, wflags: 0},
    {2, 6, ZPX, "SLO", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "CLC", rflags: 0, wflags: 0},
    {3, 4, ABY, "ORA", rflags: 0, wflags: 0},
    {1, 2, IMP, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 7, ABY, "SLO", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "ORA", rflags: 0, wflags: 0},
    {3, 7, ABX, "ASL", rflags: 0, wflags: 0},
    {3, 7, ABX, "SLO", rflags: 0, wflags: 0, unofficial : 1},
    {3, 6, ABS, "JSR", rflags: 0, wflags: 0},
    {2, 6, INX, "AND", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 8, INX, "RLA", rflags: 0, wflags: 0, unofficial : 1},
    {2, 3, ZPG, "BIT", rflags: 0, wflags: 0},
    {2, 3, ZPG, "AND", rflags: 0, wflags: 0},
    {2, 5, ZPG, "ROL", rflags: 0, wflags: 0},
    {2, 5, ZPG, "RLA", rflags: 0, wflags: 0, unofficial : 1},
    {1, 4, IMP, "PLP", rflags: 0, wflags: 0},
    {2, 2, IMM, "AND", rflags: 0, wflags: 0},
    {1, 2, ACC, "ROL", rflags: 0, wflags: 0},
    {2, 2, IMM, "AAC", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABS, "BIT", rflags: 0, wflags: 0},
    {3, 4, ABS, "AND", rflags: 0, wflags: 0},
    {3, 6, ABS, "ROL", rflags: 0, wflags: 0},
    {3, 6, ABS, "RLA", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, REL, "BMI", rflags: 0, wflags: 0},
    {2, 5, INY, "AND", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 8, INY, "RLA", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "AND", rflags: 0, wflags: 0},
    {2, 6, ZPX, "ROL", rflags: 0, wflags: 0},
    {2, 6, ZPX, "RLA", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "SEC", rflags: 0, wflags: 0},
    {3, 4, ABY, "AND", rflags: 0, wflags: 0},
    {1, 2, IMP, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 7, ABY, "RLA", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "AND", rflags: 0, wflags: 0},
    {3, 7, ABX, "ROL", rflags: 0, wflags: 0},
    {3, 7, ABX, "RLA", rflags: 0, wflags: 0, unofficial : 1},
    {1, 6, IMP, "RTI", rflags: 0, wflags: 0},
    {2, 6, INX, "EOR", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 8, INX, "SRE", rflags: 0, wflags: 0, unofficial : 1},
    {2, 3, ZPG, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 3, ZPG, "EOR", rflags: 0, wflags: 0},
    {2, 5, ZPG, "LSR", rflags: 0, wflags: 0},
    {2, 5, ZPG, "SRE", rflags: 0, wflags: 0, unofficial : 1},
    {1, 3, IMP, "PHA", rflags: 0, wflags: 0},
    {2, 2, IMM, "EOR", rflags: 0, wflags: 0},
    {1, 2, ACC, "LSR", rflags: 0, wflags: 0},
    {2, 2, IMM, "ASR", rflags: 0, wflags: 0, unofficial : 1},
    {3, 3, ABS, "JMP", rflags: 0, wflags: 0},
    {3, 4, ABS, "EOR", rflags: 0, wflags: 0},
    {3, 6, ABS, "LSR", rflags: 0, wflags: 0},
    {3, 6, ABS, "SRE", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, REL, "BVC", rflags: 0, wflags: 0},
    {2, 5, INY, "EOR", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 8, INY, "SRE", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "EOR", rflags: 0, wflags: 0},
    {2, 6, ZPX, "LSR", rflags: 0, wflags: 0},
    {2, 6, ZPX, "SRE", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "CLI", rflags: 0, wflags: 0},
    {3, 4, ABY, "EOR", rflags: 0, wflags: 0},
    {1, 2, IMP, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 7, ABY, "SRE", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "EOR", rflags: 0, wflags: 0},
    {3, 7, ABX, "LSR", rflags: 0, wflags: 0},
    {3, 7, ABX, "SRE", rflags: 0, wflags: 0, unofficial : 1},
    {1, 6, IMP, "RTS", rflags: 0, wflags: 0},
    {2, 6, INX, "ADC", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 8, INX, "RRA", rflags: 0, wflags: 0, unofficial : 1},
    {2, 3, ZPG, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 3, ZPG, "ADC", rflags: 0, wflags: 0},
    {2, 5, ZPG, "ROR", rflags: 0, wflags: 0},
    {2, 5, ZPG, "RRA", rflags: 0, wflags: 0, unofficial : 1},
    {1, 4, IMP, "PLA", rflags: 0, wflags: 0},
    {2, 2, IMM, "ADC", rflags: 0, wflags: 0},
    {1, 2, ACC, "ROR", rflags: 0, wflags: 0},
    {2, 2, IMM, "ARR", rflags: 0, wflags: 0, unofficial : 1},
    {3, 5, IND, "JMP", rflags: 0, wflags: 0},
    {3, 4, ABS, "ADC", rflags: 0, wflags: 0},
    {3, 6, ABS, "ROR", rflags: 0, wflags: 0},
    {3, 6, ABS, "RRA", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, REL, "BVS", rflags: 0, wflags: 0},
    {2, 5, INY, "ADC", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 8, INY, "RRA", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "ADC", rflags: 0, wflags: 0},
    {2, 6, ZPX, "ROR", rflags: 0, wflags: 0},
    {2, 6, ZPX, "RRA", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "SEI", rflags: 0, wflags: 0},
    {3, 4, ABY, "ADC", rflags: 0, wflags: 0},
    {1, 2, IMP, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 7, ABY, "RRA", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "ADC", rflags: 0, wflags: 0},
    {3, 7, ABX, "ROR", rflags: 0, wflags: 0},
    {3, 7, ABX, "RRA", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, IMM, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 6, INX, "STA", rflags: 0, wflags: 0},
    {2, 2, IMM, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 6, INX, "SAX", rflags: 0, wflags: 0, unofficial : 1},
    {2, 3, ZPG, "STY", rflags: 0, wflags: 0},
    {2, 3, ZPG, "STA", rflags: 0, wflags: 0},
    {2, 3, ZPG, "STX", rflags: 0, wflags: 0},
    {2, 3, ZPG, "SAX", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "DEY", rflags: 0, wflags: 0},
    {2, 2, IMM, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "TXA", rflags: 0, wflags: 0},
    {2, 2, IMM, "ANE", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABS, "STY", rflags: 0, wflags: 0},
    {3, 4, ABS, "STA", rflags: 0, wflags: 0},
    {3, 4, ABS, "STX", rflags: 0, wflags: 0},
    {3, 4, ABS, "SAX", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, REL, "BCC", rflags: 0, wflags: 0},
    {2, 6, INY, "STA", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 5, INY, "SHA", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "STY", rflags: 0, wflags: 0},
    {2, 4, ZPX, "STA", rflags: 0, wflags: 0},
    {2, 4, ZPY, "STX", rflags: 0, wflags: 0},
    {2, 4, ZPY, "SAX", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "TYA", rflags: 0, wflags: 0},
    {3, 5, ABY, "STA", rflags: 0, wflags: 0},
    {1, 2, IMP, "TXS", rflags: 0, wflags: 0},
    {3, 4, ABY, "SHS", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "SHY", rflags: 0, wflags: 0, unofficial : 1},
    {3, 5, ABX, "STA", rflags: 0, wflags: 0},
    {3, 4, ABY, "SHX", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABY, "SHA", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, IMM, "LDY", rflags: 0, wflags: 0},
    {2, 6, INX, "LDA", rflags: 0, wflags: 0},
    {2, 2, IMM, "LDX", rflags: 0, wflags: 0},
    {2, 6, INX, "LAX", rflags: 0, wflags: 0, unofficial : 1},
    {2, 3, ZPG, "LDY", rflags: 0, wflags: 0},
    {2, 3, ZPG, "LDA", rflags: 0, wflags: 0},
    {2, 3, ZPG, "LDX", rflags: 0, wflags: 0},
    {2, 3, ZPG, "LAX", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "TAY", rflags: 0, wflags: 0},
    {2, 2, IMM, "LDA", rflags: 0, wflags: 0},
    {1, 2, IMP, "TAX", rflags: 0, wflags: 0},
    {2, 2, IMM, "ATX", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABS, "LDY", rflags: 0, wflags: 0},
    {3, 4, ABS, "LDA", rflags: 0, wflags: 0},
    {3, 4, ABS, "LDX", rflags: 0, wflags: 0},
    {3, 4, ABS, "LAX", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, REL, "BCS", rflags: 0, wflags: 0},
    {2, 5, INY, "LDA", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 5, INY, "LAX", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "LDY", rflags: 0, wflags: 0},
    {2, 4, ZPX, "LDA", rflags: 0, wflags: 0},
    {2, 4, ZPY, "LDX", rflags: 0, wflags: 0},
    {2, 4, ZPY, "LAX", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "CLV", rflags: 0, wflags: 0},
    {3, 4, ABY, "LDA", rflags: 0, wflags: 0},
    {1, 2, IMP, "TSX", rflags: 0, wflags: 0},
    {3, 4, ABY, "LAS", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "LDY", rflags: 0, wflags: 0},
    {3, 4, ABX, "LDA", rflags: 0, wflags: 0},
    {3, 4, ABY, "LDX", rflags: 0, wflags: 0},
    {3, 4, ABY, "LAX", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, IMM, "CPY", rflags: 0, wflags: 0},
    {2, 6, INX, "CMP", rflags: 0, wflags: 0},
    {2, 2, IMM, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 8, INX, "DCP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 3, ZPG, "CPY", rflags: 0, wflags: 0},
    {2, 3, ZPG, "CMP", rflags: 0, wflags: 0},
    {2, 5, ZPG, "DEC", rflags: 0, wflags: 0},
    {2, 5, ZPG, "DCP", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "INY", rflags: 0, wflags: 0},
    {2, 2, IMM, "CMP", rflags: 0, wflags: 0},
    {1, 2, IMP, "DEX", rflags: 0, wflags: 0},
    {2, 2, IMM, "AXS", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABS, "CPY", rflags: 0, wflags: 0},
    {3, 4, ABS, "CMP", rflags: 0, wflags: 0},
    {3, 6, ABS, "DEC", rflags: 0, wflags: 0},
    {3, 6, ABS, "DCP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, REL, "BNE", rflags: 0, wflags: 0},
    {2, 5, INY, "CMP", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 8, INY, "DCP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "CMP", rflags: 0, wflags: 0},
    {2, 6, ZPX, "DEC", rflags: 0, wflags: 0},
    {2, 6, ZPX, "DCP", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "CLD", rflags: 0, wflags: 0},
    {3, 4, ABY, "CMP", rflags: 0, wflags: 0},
    {1, 2, IMP, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 7, ABY, "DCP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "CMP", rflags: 0, wflags: 0},
    {3, 7, ABX, "DEC", rflags: 0, wflags: 0},
    {3, 7, ABX, "DCP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, IMM, "CPX", rflags: 0, wflags: 0},
    {2, 6, INX, "SBC", rflags: 0, wflags: 0},
    {2, 2, IMM, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 8, INX, "ISB", rflags: 0, wflags: 0, unofficial : 1},
    {2, 3, ZPG, "CPX", rflags: 0, wflags: 0},
    {2, 3, ZPG, "SBC", rflags: 0, wflags: 0},
    {2, 5, ZPG, "INC", rflags: 0, wflags: 0},
    {2, 5, ZPG, "ISB", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "INX", rflags: 0, wflags: 0},
    {2, 2, IMM, "SBC", rflags: 0, wflags: 0},
    {1, 2, IMP, "NOP", rflags: 0, wflags: 0},
    {2, 2, IMM, "SBC", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABS, "CPX", rflags: 0, wflags: 0},
    {3, 4, ABS, "SBC", rflags: 0, wflags: 0},
    {3, 6, ABS, "INC", rflags: 0, wflags: 0},
    {3, 6, ABS, "ISB", rflags: 0, wflags: 0, unofficial : 1},
    {2, 2, REL, "BEQ", rflags: 0, wflags: 0},
    {2, 5, INY, "SBC", rflags: 0, wflags: 0},
    {1, 0, IMP, "???", rflags: 0, wflags: 0, unofficial: 1, jam: 1},
    {2, 8, INY, "ISB", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {2, 4, ZPX, "SBC", rflags: 0, wflags: 0},
    {2, 6, ZPX, "INC", rflags: 0, wflags: 0},
    {2, 6, ZPX, "ISB", rflags: 0, wflags: 0, unofficial : 1},
    {1, 2, IMP, "SED", rflags: 0, wflags: 0},
    {3, 4, ABY, "SBC", rflags: 0, wflags: 0},
    {1, 2, IMP, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 7, ABY, "ISB", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "NOP", rflags: 0, wflags: 0, unofficial : 1},
    {3, 4, ABX, "SBC", rflags: 0, wflags: 0},
    {3, 7, ABX, "INC", rflags: 0, wflags: 0},
    {3, 7, ABX, "ISB", rflags: 0, wflags: 0, unofficial : 1},
};

};
};
